djavanm/Bookify

src/components/App/App.js, src/components/LoginForm/LoginForm.js, src/components/Nav/Nav.js
Started working on some components, wanna merge @SamanthaLFreeman ?
=> Component setup1

src/components/App/App.js, src/components/Book/Book.js, src/components/BookContainer/BookContainer.js, src/components/SearchForm/SearchForm.js
Set up initial components for BookContainer, Book and SearchForm.
=> Component setup2

src/components/App/App.js, src/util/apiCalls.js
Setup initial fetch call in the componentDidMount in the App.
=> Add initial fetch setup

package-lock.json, package.json, src/actions/index.js, src/components/App/App.js, src/containers/SearchForm/SearchForm.js, src/index.js, src/reducers/index.js, src/reducers/search.js, src/util/apiCalls.js
Let me know what you think, friend!
=> Search action1

src/actions/index.js, src/components/Nav/Nav.js, src/containers/App/App.js, src/containers/LoginForm/LoginForm.js, src/reducers/currentUser.js, src/reducers/index.js
Hey Sam, Here's the branch which adds our action to create the new user and add to store.
=> Store current user

src/containers/LoginForm/LoginForm.js, src/util/apiCalls.js
This branch adds the existing User after a POST is made.
=> Create functionality which posts the existing user and displays on the DOM

src/containers/App/App.js, src/util/apiCalls.js
This branch sets up our fetch request, which deletes a specific book for the user. In addition, the store updates removing the same book from the favorites array.
=> Create a DELETE request

src/components/BookContainer/BookContainer.js, src/containers/App/App.js, src/containers/Book/Book.js, src/containers/Nav/Nav.js, src/styles/_Book.scss
Add basic styling for the favorite button that lets you know if the book has been favorited.
=> Display favorites

src/actions/index.js, src/components/BookContainer/BookContainer.js, src/containers/App/App.js, src/containers/LoginForm/LoginForm.js, src/containers/Nav/Nav.js, src/reducers/genreFilter.js, src/reducers/genres.js, src/reducers/index.js
This branch creates a dynamic array listing all of the genres that have been favorited by the user.
=> Filter genres

src/components/BookContainer/BookContainer.js, src/containers/Nav/Nav.js
We can filter the my-collection cards based on the genre! We just need to possible revamp into a drop down menu?
=> Attach filter actions to book Container

package-lock.json, package.json, src/actions/actions.test.js, src/setupTests.js
This branch adds all of the tests for the action creators along with downloads any dependencies needed later for testing.
=> Action creator tests

src/components/BookDetails/BookDetails.js, src/containers/App/App.js, src/containers/Book/Book.js
Added the component that will display the Nav and a brief description about each book that you click. This uses dynamic routing created from the App container.
=> Book details

package-lock.json, package.json, src/components/BookDetails/BookDetails.js, src/util/apiCalls.js
For this branch I set up interweave, which helps convert the description string from the api to HTML.
=> Fix description displayed for book details

src/actions/index.js, src/components/BookContainer/BookContainer.js, src/containers/App/App.js, src/containers/BookContainer/BookContainer.js, src/containers/SearchForm/SearchForm.js, src/reducers/index.js, src/reducers/searchFilter.js
Added logic to book container that allows it to render the show next or show previous books based on the current search results. The book container will now only display 10 books at a time.
=> Display ten

src/actions/actions.test.js, src/reducers/currentUser.test.js, src/reducers/favorites.test.js, src/reducers/genreFilter.test.js, src/reducers/genres.test.js, src/reducers/search.test.js, src/reducers/searchFilter.test.js
This branch adds the tests for the recently added action creators along with tests for all of the reducer files.
=> Reducer tests

src/components/BookDetails/BookDetails.js, src/components/BookDetails/BookDetails.test.js, src/components/BookDetails/__snapshots__/BookDetails.test.js.snap, src/containers/App/App.test.js, src/containers/Book/Book.js
- Removed any book or bookDetails that were flagged for not being used by eslint
- Added snapshot test for the one component (bookDetails) and fixed the App's initial test, which was broken from Provider and Browser Router being wrapped around App in index.js
=> Component test

src/containers/App/App.js
Fixed issue when logging out at my collection, will now render a redirect to the home route when user logs out from the my-collection route.
=> Add conditional rendering to my-collection route

src/util/apiCalls.js, src/util/apiCalls.test.js
Added all happy and sad path testing for our apiCalls
=> Api calls tests

src/containers/LoginForm/LoginForm.js, src/styles/_LoginForm.scss, src/styles/_variables.scss
Add styling for Login Form. In addition, add message to form to clarify if it is login vs. signup.
=> Login form css

src/containers/Book/Book.js, src/containers/BookContainer/BookContainer.js, src/containers/Nav/Nav.js, src/styles/_Book.scss, src/styles/_BookContainer.scss, src/styles/_Nav.scss, src/styles/_SearchForm.scss, src/styles/_variables.scss
Clean up the individual book styling and favorite button. In addition, added touches of green throughout the project.
=> Books styling

src/containers/Nav/Nav.js, src/styles/_Nav.scss
Move the genres buttons under the nav and set them up to wrap as the size of the page changes.
=> Clean up genres buttons on my-collection

src/components/BookDetails/BookDetails.js, src/containers/Book/Book.js, src/styles/_Book.scss, src/styles/_BookDetails.scss
Cleans up the following CSS:
1. Creates margin for the book details
2. Changes the link to book details
3. Adds a back button to return to '/'
=> CSS book details

src/containers/App/App.js, src/containers/App/App.test.js, src/containers/Book/Book.js, src/containers/Book/Book.test.js, src/containers/BookContainer/BookContainer.js, src/containers/BookContainer/BookContainer.test.js, src/containers/LoginForm/LoginForm.js, src/containers/LoginForm/LoginForm.test.js, src/containers/LoginForm/__snapshots__/LoginForm.test.js.snap, src/containers/Nav/Nav.js, src/containers/Nav/Nav.test.js, src/containers/Nav/__snapshots__/Nav.test.js.snap, src/containers/SearchForm/SearchForm.js, src/containers/SearchForm/SearchForm.test.js, src/containers/SearchForm/__snapshots__/SearchForm.test.js.snap
Added test and propType tests for all containers.
=> Container testing

src/containers/App/App.js, src/containers/App/App.test.js, src/containers/Nav/Nav.js, src/containers/Nav/Nav.test.js, src/containers/Nav/__snapshots__/Nav.test.js.snap, src/reducers/currentUser.js
Set up logged in user to persist on page load with localStorage. Then is removed from localStorage when the user is logged out.
=> Persist current user

src/containers/App/App.js, src/reducers/currentUser.test.js
Added functionality that calls for the favorites array if a current user exists in local storage.
=> Fix issue with reloading page 

src/containers/App/App.js, src/containers/App/App.test.js, src/containers/LoginForm/LoginForm.js, src/containers/Nav/Nav.test.js, src/containers/SearchForm/SearchForm.js
Create router test for LoginForm and fix error messages for PropTypes.
=> Router testing

README.md
This branch sets up the readme with snapshots.
=> Create initial readme
